(()=>{
const cfg=window.KIVOPAY_CONFIG||{},db=window.supabase&&cfg.supabaseUrl&&cfg.supabaseAnonKey?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0)),date=v=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'-';
let data={users:[],deposits:[],transactions:[],stats:{}};
async function api(options={}){if(!db)throw new Error('Supabase belum dikonfigurasi.');const{data:{session}}=await db.auth.getSession();if(!session)throw new Error('Sesi admin berakhir.');const r=await fetch('/api/admin-wallet',{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,...(options.headers||{})}}),b=await r.json().catch(()=>({}));if(!r.ok||b.ok===false)throw new Error(b.message||`HTTP ${r.status}`);return b}
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function renderStats(){setText('#walletStatBalance',money(data.stats.total_balance));setText('#walletStatDeposit',money(data.stats.total_deposit));setText('#walletStatCompleted',data.stats.completed_deposits||0);setText('#walletStatPending',data.stats.pending_deposits||0)}
function renderSelect(){const el=$('#walletUserSelect');if(!el)return;const value=el.value;el.innerHTML='<option value="">Pilih pengguna</option>'+data.users.map(u=>`<option value="${esc(u.user_id)}">${esc(u.display_name)} — ${esc(u.email||u.username||'')} (${money(u.balance)})</option>`).join('');el.value=value}
function renderUsers(){const root=$('#walletUsersList');if(!root)return;const q=($('#walletUserSearch')?.value||'').toLowerCase();const rows=data.users.filter(u=>!q||`${u.display_name} ${u.email} ${u.username}`.toLowerCase().includes(q));root.innerHTML=rows.length?rows.map(u=>`<button type="button" class="wallet-user-row" data-wallet-user="${esc(u.user_id)}"><span><b>${esc(u.display_name)}</b><small>${esc(u.email||u.username||'-')}</small></span><strong>${money(u.balance)}</strong></button>`).join(''):'<p class="muted">Pengguna tidak ditemukan.</p>';root.querySelectorAll('[data-wallet-user]').forEach(b=>b.onclick=()=>{const s=$('#walletUserSelect');s.value=b.dataset.walletUser;s.scrollIntoView({behavior:'smooth',block:'center'})})}
function statusText(s){return({completed:'Berhasil',pending:'Pending',expired:'Kedaluwarsa',failed:'Gagal'})[s]||s}
function renderDeposits(){const root=$('#walletDepositsList');if(!root)return;const q=($('#walletDepositSearch')?.value||'').toLowerCase(),st=$('#walletDepositStatus')?.value||'';const rows=data.deposits.filter(d=>(!st||d.status===st)&&(!q||`${d.invoice} ${d.display_name} ${d.email}`.toLowerCase().includes(q)));root.innerHTML=rows.length?rows.map(d=>`<article class="wallet-history-row"><div><b>${esc(d.invoice)}</b><small>${esc(d.display_name)} · ${esc(d.email||'-')}</small></div><div><strong>${money(d.amount)}</strong><small>${date(d.created_at)}</small></div><span class="wallet-status ${esc(d.status)}">${esc(statusText(d.status))}</span></article>`).join(''):'<p class="muted">Belum ada deposit yang sesuai.</p>'}
function renderTransactions(){const root=$('#walletTransactionsList');if(!root)return;root.innerHTML=data.transactions.length?data.transactions.map(t=>`<article class="wallet-history-row"><div><b>${esc(t.description||t.reference)}</b><small>${esc(t.display_name)} · ${esc(t.reference)}</small></div><div><strong class="${Number(t.amount)>=0?'wallet-plus':'wallet-minus'}">${Number(t.amount)>=0?'+':''}${money(t.amount)}</strong><small>Saldo akhir ${money(t.balance_after)} · ${date(t.created_at)}</small></div><span class="wallet-status ${esc(t.type)}">${esc(t.type)}</span></article>`).join(''):'<p class="muted">Belum ada transaksi saldo.</p>'}
async function load(){setText('#walletAdjustMessage','Memuat daftar pengguna...');try{const result=await api();data={users:result.users||[],deposits:result.deposits||[],transactions:result.transactions||[],stats:result.stats||{}};renderStats();renderSelect();renderUsers();renderDeposits();renderTransactions();const warning=(result.warnings||[]).join(' • ');setText('#walletAdjustMessage',data.users.length?(warning||`${data.users.length} pengguna berhasil dimuat.`):'Belum ada akun pengguna yang dapat dimuat.')}catch(e){setText('#walletAdjustMessage',e.message)}}
$('#walletAdjustForm')?.addEventListener('submit',async e=>{e.preventDefault();const user_id=$('#walletUserSelect').value,operation=document.querySelector('input[name="walletOperation"]:checked')?.value,amount=Number(String($('#walletAmount').value).replace(/\D/g,'')),reason=$('#walletReason').value.trim(),btn=$('#walletAdjustSubmit');if(!confirm(`${operation==='add'?'Tambah':'Kurangi'} saldo sebesar ${money(amount)}?`))return;btn.disabled=true;setText('#walletAdjustMessage','Menyimpan perubahan...');try{const b=await api({method:'POST',body:JSON.stringify({user_id,operation,amount,reason})});setText('#walletAdjustMessage',b.message);e.target.reset();document.querySelector('input[name="walletOperation"][value="add"]').checked=true;await load()}catch(err){setText('#walletAdjustMessage',err.message)}finally{btn.disabled=false}});
const amountInput=$('#walletAmount');amountInput?.addEventListener('input',()=>{const digits=amountInput.value.replace(/\D/g,'').slice(0,12);amountInput.value=digits?new Intl.NumberFormat('id-ID').format(Number(digits)):''});
$('#refreshAdminWallet')?.addEventListener('click',load);$('#walletUserSearch')?.addEventListener('input',renderUsers);$('#walletDepositSearch')?.addEventListener('input',renderDeposits);$('#walletDepositStatus')?.addEventListener('change',renderDeposits);document.querySelector('[data-admin-page-btn="wallet"]')?.addEventListener('click',load);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
