(()=>{
 const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const input=document.querySelector('#depositAmount'),form=document.querySelector('#depositForm'),message=document.querySelector('#depositMessage'),submit=document.querySelector('#createDepositBtn');
 let session=null, polling=false;
 const parseAmount=()=>Number(String(input.value||'').replace(/[^0-9]/g,''));
 function renderSummary(){const amount=parseAmount();document.querySelector('#summaryAmount').textContent=rupiah(amount);document.querySelector('#summaryTotal').textContent=rupiah(amount);}
 document.querySelectorAll('[data-amount]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-amount]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');input.value=Number(btn.dataset.amount).toLocaleString('id-ID');renderSummary();});
 input.addEventListener('input',()=>{const value=parseAmount();input.value=value?value.toLocaleString('id-ID'):'';document.querySelectorAll('[data-amount]').forEach(x=>x.classList.toggle('active',Number(x.dataset.amount)===value));renderSummary();});
 async function headers(json=false){return KivoAuth.authHeaders(json?{'Content-Type':'application/json'}:{});}
 async function api(url,options={}){const response=await fetch(url,{cache:'no-store',...options,headers:{...(await headers(!!options.body)),...(options.headers||{})}});const raw=await response.text();let data={};try{data=raw?JSON.parse(raw):{};}catch{}if(!response.ok)throw new Error(data.error||'Terjadi kesalahan pada server.');return data;}
 async function loadHistory(){const box=document.querySelector('#depositHistoryList');try{const data=await api('/api/deposit-history');document.querySelector('#depositBalance').textContent=rupiah(data.balance);document.querySelector('#balanceHint').textContent='Siap digunakan untuk transaksi berikutnya.';const labels={pending:'Menunggu',completed:'Berhasil',expired:'Kedaluwarsa',cancelled:'Dibatalkan',failed:'Gagal'};box.innerHTML=data.deposits.length?data.deposits.map(d=>`<article class="deposit-row"><div><strong>${esc(d.invoice)}</strong><small>${new Date(d.created_at).toLocaleString('id-ID')}</small></div><div><strong>${rupiah(d.amount)}</strong><small>Saldo masuk</small></div><div><strong>${rupiah(d.payment_amount)}</strong><small>Total bayar</small></div><span class="deposit-status ${esc(d.status)}">${esc(labels[d.status]||d.status)}</span></article>`).join(''):'<p class="history-empty">Belum ada riwayat deposit.</p>';}catch(e){box.innerHTML=`<p class="history-empty">${esc(e.message)}</p>`;}}
 function showPayment(deposit){document.querySelector('#depositPaymentModal')?.remove();const modal=document.createElement('div');modal.id='depositPaymentModal';modal.className='deposit-modal';modal.innerHTML=`<div class="deposit-modal-bg"></div><section><header><div><small>INVOICE DEPOSIT</small><h2>${esc(deposit.invoice)}</h2></div><button type="button" data-close>×</button></header><p>Scan QRIS dan bayar tepat sesuai nominal di bawah.</p><div id="depositQr" class="deposit-qr"></div><div class="deposit-total"><span>Total pembayaran</span><strong>${rupiah(deposit.payment_amount)}</strong><small>Saldo yang masuk: ${rupiah(deposit.amount)}</small></div><div id="depositLiveStatus" class="deposit-live pending">Menunggu pembayaran...</div><footer><button type="button" id="copyDepositInvoice">Salin Invoice</button><button type="button" data-close>Tutup</button></footer></section>`;document.body.appendChild(modal);const qr=modal.querySelector('#depositQr');if(deposit.qr_image)qr.innerHTML=`<img src="${esc(deposit.qr_image)}" alt="QRIS deposit">`;else if(deposit.qr_content&&window.QRCode)new QRCode(qr,{text:deposit.qr_content,width:260,height:260});else qr.textContent='QRIS belum tersedia.';modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.remove());modal.querySelector('#copyDepositInvoice').onclick=async()=>{await navigator.clipboard.writeText(deposit.invoice);modal.querySelector('#copyDepositInvoice').textContent='Tersalin ✓';};pollDeposit(deposit.invoice,modal);}
 async function pollDeposit(invoice,modal){if(polling)return;polling=true;const status=modal.querySelector('#depositLiveStatus');while(document.body.contains(modal)){try{const data=await api('/api/check-deposit?invoice='+encodeURIComponent(invoice));const d=data.deposit;status.className='deposit-live '+d.status;if(d.status==='completed'){status.textContent='Deposit berhasil. Saldo sudah ditambahkan.';await loadHistory();polling=false;return;}if(['expired','cancelled','failed'].includes(d.status)){status.textContent=d.status==='expired'?'Invoice kedaluwarsa.':'Deposit tidak dapat diproses.';polling=false;return;}status.textContent='Menunggu pembayaran dan mencocokkan mutasi...';}catch(e){status.textContent='Mengecek ulang pembayaran...';}await new Promise(r=>setTimeout(r,4000));}polling=false;}
 form.onsubmit=async e=>{e.preventDefault();const amount=parseAmount();message.className='deposit-message';message.textContent='';if(amount<10000||amount>2000000||amount%1000!==0){message.textContent='Nominal harus Rp10.000–Rp2.000.000 dan kelipatan Rp1.000.';return;}submit.disabled=true;submit.querySelector('span').textContent='Membuat QRIS...';try{const data=await api('/api/create-deposit',{method:'POST',body:JSON.stringify({amount})});message.className='deposit-message success';message.textContent='Invoice berhasil dibuat.';showPayment(data.deposit);await loadHistory();}catch(err){message.textContent=err.message;}finally{submit.disabled=false;submit.querySelector('span').textContent='Buat Deposit';}};
 document.querySelector('#refreshDeposits').onclick=loadHistory;
 (async()=>{session=await KivoAuth.session();if(!session)return location.replace('login.html');loadHistory();})();
})();
