(()=>{
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])), rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
let services=[],catalog=[],selectedGame='';
const fallbackImage='https://img2.pixhost.to/images/9481/751089580_papaqueen.jpg';
async function jsonFetch(url,opt){const r=await fetch(url,opt);const t=await r.text();let d={};try{d=t?JSON.parse(t):{};}catch{throw new Error('Respons server tidak valid.');}if(!r.ok)throw new Error(d.error||'Terjadi kesalahan.');return d;}
async function load(){const [srv,cat]=await Promise.all([jsonFetch('/api/game-services'),jsonFetch('/api/game-catalog').catch(()=>({games:[]}))]);services=srv.services||[];catalog=cat.games||[];renderGames();}
function gameNames(){return [...new Set(services.map(x=>x.game).filter(Boolean))].sort();}
function conf(name){return catalog.find(x=>String(x.vip_brand).toLowerCase()===String(name).toLowerCase())||{};}
function renderGames(){const q=$('#gameSearch').value.trim().toLowerCase();const names=gameNames().filter(n=>n.toLowerCase().includes(q));$('#gameGrid').innerHTML=names.length?names.map((n,i)=>{const c=conf(n);return `<button class="game-card" data-game="${esc(n)}"><img src="${esc(c.image_url||fallbackImage)}" alt="${esc(c.display_name||n)}"><strong>${esc(c.display_name||n)}</strong><span>${services.filter(s=>s.game===n).length} paket</span></button>`}).join(''):'<p>Tidak ada game ditemukan.</p>';document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));}
function sellPrice(cost){return Number(cost)+Math.max(500,Math.ceil(Number(cost)*0.05));}
function openGame(name){selectedGame=name;const c=conf(name);$('#selectedGameName').textContent=c.display_name||name;$('#selectedGameImage').src=c.image_url||fallbackImage;const rows=services.filter(x=>x.game===name).sort((a,b)=>a.price-b.price);$('#gameService').innerHTML=rows.map(x=>`<option value="${esc(x.code)}" data-cost="${x.price}">${esc(x.name)} — ${rupiah(sellPrice(x.price))}</option>`).join('');$('#gameCheckout').hidden=false;$('#gameCheckout').scrollIntoView({behavior:'smooth',block:'start'});updatePrice();}
function selected(){return services.find(x=>x.code===$('#gameService').value);}
function updatePrice(){const s=selected();$('#gameSellPrice').textContent=rupiah(sellPrice(s?.price||0));$('#selectedGameInfo').textContent=s?.description||'Isi data tujuan dengan benar.';}
$('#gameSearch').addEventListener('input',renderGames);$('#gameService').addEventListener('change',updatePrice);$('#closeGameCheckout').onclick=()=>$('#gameCheckout').hidden=true;
$('#checkNicknameBtn').onclick=async()=>{const s=selected(),target=$('#gameTarget').value.trim(),zone=$('#gameZone').value.trim();if(!target)return $('#nicknameResult').textContent='Isi ID dulu.';$('#nicknameResult').textContent='Mengecek nickname...';try{const d=await jsonFetch('/api/game-nickname',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:s?.code,target,zone})});$('#nicknameResult').textContent='✓ '+(d.nickname||'ID ditemukan');}catch(e){$('#nicknameResult').textContent='⚠ '+e.message;}};
$('#gameOrderForm').onsubmit=async e=>{e.preventDefault();const btn=$('#submitGameOrder');btn.disabled=true;btn.textContent='Membuat QRIS...';$('#gameFormMessage').textContent='';try{const d=await jsonFetch('/api/create-game-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service:$('#gameService').value,target:$('#gameTarget').value.trim(),zone:$('#gameZone').value.trim(),customer_name:$('#gameCustomerName').value.trim(),customer_contact:$('#gameCustomerContact').value.trim()})});sessionStorage.setItem('kivopay_game_payment_'+d.order.invoice,JSON.stringify(d.order));location.href='payment-game.html?invoice='+encodeURIComponent(d.order.invoice);}catch(err){$('#gameFormMessage').textContent=err.message;btn.disabled=false;btn.textContent='Buat QRIS';}};
load().catch(e=>$('#gameGrid').innerHTML=`<p>${esc(e.message)}</p>`);
})();
