(()=>{
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const plainText=v=>{const doc=new DOMParser().parseFromString(String(v??''),'text/html');return (doc.body.textContent||'').replace(/\s+/g,' ').trim();};
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const fallbackImage='https://img2.pixhost.to/images/9481/751089580_papaqueen.jpg';
let services=[],catalog=[],selectedService=null,currentCategory='games',activeGame='',activeConfig={},activeSchema=[];
async function jsonFetch(url,opt){const r=await fetch(url,opt);const t=await r.text();let d={};try{d=t?JSON.parse(t):{};}catch{throw new Error('Respons server tidak valid.');}if(!r.ok)throw new Error(d.error||'Terjadi kesalahan.');return d;}
function conf(name){return catalog.find(x=>String(x.vip_brand).toLowerCase()===String(name).toLowerCase())||{};}
function gameNames(){return [...new Set(services.map(x=>x.game).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'id'));}
function categoryOf(name){const n=String(name).toLowerCase(),streaming=['iqiyi','netflix','spotify','youtube','viu','vidio','wetv','disney','prime video','hbo','canva','capcut','alight motion','bstation','vision+','mola','loklok'],voucher=['voucher','gift card','steam wallet','google play','itunes','playstation','xbox','garena shells','razergold','wallet'],games=['mobile legends','free fire','genshin','valorant','pubg','honor of kings','roblox','ace racer','tower of fantasy','zenless','honkai','call of duty','arena breakout','point blank','fc mobile','efootball','clash','minecraft','zepeto','afk journey','age of empires'];if(streaming.some(k=>n.includes(k)))return'streaming';if(voucher.some(k=>n.includes(k)))return'voucher';if(games.some(k=>n.includes(k)))return'games';return'lainnya';}
function displayPrice(s){return Number(s?.sell_price??(Number(s?.price||0)+(Number(s?.price||0)<10000?2000:3000)));}
async function loadData(){const[srv,cat]=await Promise.all([jsonFetch('/api/game-services'),jsonFetch('/api/game-catalog').catch(()=>({games:[]}))]);services=srv.services||[];catalog=cat.games||[];}
function renderCatalog(){const grid=$('#gameGrid');if(!grid)return;const q=$('#gameSearch').value.trim().toLowerCase(),names=gameNames().filter(n=>categoryOf(n)===currentCategory&&n.toLowerCase().includes(q)),titles={games:['KATALOG GAME','Game Populer'],streaming:['HIBURAN','Streaming Premium'],voucher:['VOUCHER DIGITAL','Voucher'],lainnya:['PRODUK DIGITAL','Lainnya']};$('#categoryEyebrow').textContent=titles[currentCategory][0];$('#categoryTitle').textContent=titles[currentCategory][1];grid.innerHTML=names.length?names.map(n=>{const c=conf(n),count=services.filter(s=>s.game===n).length,title=c.display_name||n;return`<a class="vip-card" href="game-detail.html?game=${encodeURIComponent(n)}"><img src="${esc(c.image_url||fallbackImage)}" alt="${esc(title)}"><span class="vip-card-title">${esc(title)}</span><small>${count} paket</small></a>`}).join(''):'<div class="empty-catalog">Belum ada produk di kategori ini.</div>';}
function initCatalog(){document.querySelectorAll('.category-tab').forEach(btn=>btn.addEventListener('click',()=>{currentCategory=btn.dataset.category;document.querySelectorAll('.category-tab').forEach(x=>x.classList.toggle('active',x===btn));renderCatalog()}));$('#gameSearch').addEventListener('input',renderCatalog);loadData().then(renderCatalog).catch(e=>$('#gameGrid').innerHTML=`<div class="empty-catalog">${esc(e.message)}</div>`);}
function fallbackSchema(game){const n=String(game||'').toLowerCase(),cat=categoryOf(game);if(n.includes('mobile legends'))return[{key:'target',label:'User ID',type:'text',required:true,placeholder:'Masukkan User ID',mapTo:'target'},{key:'zone',label:'Zone ID',type:'text',required:true,placeholder:'Masukkan Zone ID',mapTo:'zone'}];if(n.includes('genshin'))return[{key:'target',label:'UID',type:'text',required:true,placeholder:'Masukkan UID',mapTo:'target'},{key:'server',label:'Server',type:'select',required:true,placeholder:'Pilih server',mapTo:'zone',options:['America','Asia','Europe','TW_HK_MO']}];if(cat==='streaming')return[{key:'email',label:'Email / Nomor Tujuan',type:'email',required:true,placeholder:'Masukkan email aktif',mapTo:'target'}];return[{key:'target',label:'User ID / ID Tujuan',type:'text',required:true,placeholder:'Masukkan ID tujuan',mapTo:'target'}];}
function normalizeSchema(v){const arr=Array.isArray(v)&&v.length?v:fallbackSchema(activeGame);return arr.map((f,i)=>({key:String(f.key||`field_${i+1}`),label:String(f.label||`Field ${i+1}`),type:['text','email','tel','password','textarea','select'].includes(f.type)?f.type:'text',required:Boolean(f.required),placeholder:String(f.placeholder||''),options:Array.isArray(f.options)?f.options:[],mapTo:String(f.mapTo||'ignore'),sensitive:Boolean(f.sensitive||f.type==='password'),help:String(f.help||'')}));}
function renderDynamicFields(schema){activeSchema=normalizeSchema(schema);const box=$('#targetFields');box.innerHTML=activeSchema.map(f=>{const req=f.required?'required':'',help=f.help?`<small class="dynamic-field-help">${esc(f.help)}</small>`:'';let control;if(f.type==='select')control=`<select data-form-key="${esc(f.key)}" ${req}><option value="">${esc(f.placeholder||'Pilih opsi')}</option>${f.options.map(o=>typeof o==='object'?`<option value="${esc(o.value)}">${esc(o.label)}</option>`:`<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select>`;else if(f.type==='textarea')control=`<textarea data-form-key="${esc(f.key)}" ${req} placeholder="${esc(f.placeholder)}"></textarea>`;else control=`<input data-form-key="${esc(f.key)}" type="${esc(f.type)}" ${req} placeholder="${esc(f.placeholder)}" autocomplete="off">`;return`<label class="field-control dynamic-field-control"><span>${esc(f.label)}${f.required?' *':''}</span>${control}${help}</label>`}).join('');restoreSavedForm();const hasNick=activeSchema.some(f=>f.mapTo==='target')&&categoryOf(activeGame)==='games'&&!activeSchema.some(f=>f.type==='password');$('#checkNicknameBtn').hidden=!hasNick;}
function formValues(){const out={};document.querySelectorAll('[data-form-key]').forEach(el=>out[el.dataset.formKey]=String(el.value||'').trim());return out;}
function mappedValue(mapTo){const fields=activeSchema.filter(f=>f.mapTo===mapTo);return fields.map(f=>formValues()[f.key]).filter(Boolean).join('|');}
function restoreSavedForm(){try{const saved=JSON.parse(localStorage.getItem('kivopay_dynamic_form_'+encodeURIComponent(activeGame))||'{}');document.querySelectorAll('[data-form-key]').forEach(el=>{if(saved[el.dataset.formKey]!=null)el.value=saved[el.dataset.formKey]})}catch{}}
let nicknameTimer=null,lastNicknameKey='';
async function checkNickname(auto=false){if(!selectedService){if(!auto)$('#nicknameResult').textContent='Pilih produk terlebih dahulu.';return false;}const target=mappedValue('target'),zone=mappedValue('zone');if(!target){if(!auto)$('#nicknameResult').textContent='Isi data tujuan terlebih dahulu.';return false;}const requiredZone=activeSchema.some(f=>f.mapTo==='zone'&&f.required);if(requiredZone&&!zone){if(!auto)$('#nicknameResult').textContent='Isi Zone ID / Server terlebih dahulu.';return false;}const key=[selectedService.code,target,zone].join('|');if(auto&&key===lastNicknameKey)return true;$('#nicknameResult').textContent='Mengecek nickname...';try{const d=await jsonFetch('/api/game-nickname',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:selectedService.code,game:selectedService.game||activeGame,target,zone})});lastNicknameKey=key;$('#nicknameResult').textContent='✓ '+(d.nickname||'ID ditemukan');return true}catch(e){lastNicknameKey='';$('#nicknameResult').textContent='⚠ '+e.message;return false}}
function scheduleNicknameCheck(){clearTimeout(nicknameTimer);nicknameTimer=setTimeout(()=>checkNickname(true),650)}
function selectService(code){selectedService=services.find(x=>x.code===code)||null;lastNicknameKey='';document.querySelectorAll('.service-option').forEach(x=>x.classList.toggle('selected',x.dataset.code===code));$('#selectedServiceName').textContent=selectedService?.name||'Pilih produk';$('#selectedServiceDescription').textContent=plainText(selectedService?.description)||'Isi data tujuan dengan benar.';$('#gameSellPrice').textContent=rupiah(displayPrice(selectedService));$('#submitGameOrder').disabled=!selectedService;if(selectedService)scheduleNicknameCheck();}
function initDetail(){activeGame=new URLSearchParams(location.search).get('game')||'';if(!activeGame){location.href='topup-game.html';return;}loadData().then(()=>{const rows=services.filter(x=>x.game===activeGame).sort((a,b)=>displayPrice(a)-displayPrice(b));activeConfig=conf(activeGame);const title=activeConfig.display_name||activeGame;document.title=`${title} — KivoPay`;$('#detailGameName').textContent=title;$('#detailGameImage').src=activeConfig.image_url||fallbackImage;$('#detailGameImage').onerror=()=>$('#detailGameImage').src=fallbackImage;$('#detailGameSummary').textContent=`${rows.length} produk tersedia. Pilih paket terbaik untuk kebutuhanmu.`;$('#detailEyebrow').textContent=categoryOf(activeGame)==='streaming'?'PRODUK DIGITAL OTOMATIS':'TOP UP OTOMATIS';renderDynamicFields(activeConfig.form_schema);document.querySelectorAll('[data-form-key]').forEach(el=>{el.addEventListener(el.tagName==='SELECT'?'change':'input',scheduleNicknameCheck)});$('#serviceGrid').innerHTML=rows.length?rows.map(s=>`<button type="button" class="service-option" data-code="${esc(s.code)}"><span>${esc(s.name)}</span><strong>${rupiah(displayPrice(s))}</strong></button>`).join(''):'<p>Produk sedang tidak tersedia.</p>';document.querySelectorAll('.service-option').forEach(b=>b.onclick=()=>selectService(b.dataset.code));}).catch(e=>$('#serviceGrid').innerHTML=`<p>${esc(e.message)}</p>`);
$('#saveTargetBtn').onclick=()=>{localStorage.setItem('kivopay_dynamic_form_'+encodeURIComponent(activeGame),JSON.stringify(formValues()));$('#nicknameResult').textContent='✓ Data berhasil disimpan di perangkat ini.';};
$('#checkNicknameBtn').onclick=()=>checkNickname(false);
let pendingOrderPayload=null;
function confirmRow(label,value){return value?`<div class="order-confirm-row"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`:'';}
function openOrderConfirmation(payload,values,customerName,contact){pendingOrderPayload=payload;const rows=[];activeSchema.forEach(f=>{const value=values[f.key];if(value&&!f.sensitive)rows.push(confirmRow(f.label,value));});rows.push(confirmRow('Produk',selectedService?.name||selectedService?.code));rows.push(confirmRow('Jumlah','1'));if(categoryOf(activeGame)!=='streaming'){rows.push(confirmRow('Nama pembeli',customerName));rows.push(confirmRow('Kontak',contact));}$('#orderConfirmDetails').innerHTML=rows.join('');$('#orderConfirmTotal').textContent=rupiah(displayPrice(selectedService));$('#orderConfirmDialog').showModal();}
async function createConfirmedOrder(){if(!pendingOrderPayload)return;const btn=$('#confirmOrderBtn'),submitBtn=$('#submitGameOrder');btn.disabled=true;btn.querySelector('span').textContent='Membuat QRIS...';submitBtn.disabled=true;$('#gameFormMessage').textContent='';try{const d=await jsonFetch('/api/create-game-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pendingOrderPayload)});sessionStorage.setItem('kivopay_game_payment_'+d.order.invoice,JSON.stringify(d.order));let history=[];try{history=JSON.parse(localStorage.getItem('kivopay_game_invoices')||'[]')}catch{}history=[d.order.invoice,...history.filter(x=>x!==d.order.invoice)].slice(0,100);localStorage.setItem('kivopay_game_invoices',JSON.stringify(history));location.href='payment-game.html?invoice='+encodeURIComponent(d.order.invoice)}catch(err){$('#orderConfirmDialog').close();$('#gameFormMessage').textContent=err.message;submitBtn.disabled=false;btn.disabled=false;btn.querySelector('span').textContent='Ya, Buat Pesanan';pendingOrderPayload=null;}}
$('#closeOrderConfirm').onclick=$('#cancelOrderConfirm').onclick=()=>{$('#orderConfirmDialog').close();pendingOrderPayload=null;};
$('#confirmOrderBtn').onclick=createConfirmedOrder;
$('#orderConfirmDialog').addEventListener('cancel',()=>{pendingOrderPayload=null;});
$('#gameOrderForm').onsubmit=e=>{e.preventDefault();if(!selectedService)return;const values=formValues(),missing=activeSchema.find(f=>f.required&&!values[f.key]);if(missing){$('#gameFormMessage').textContent=`${missing.label} wajib diisi.`;document.querySelector(`[data-form-key="${CSS.escape(missing.key)}"]`)?.focus();return;}const target=mappedValue('target'),zone=mappedValue('zone'),additional=mappedValue('additional'),simple=categoryOf(activeGame)==='streaming',customerName=simple?'Pelanggan KivoPay':$('#gameCustomerName').value.trim(),contact=simple?(target||Object.values(values)[0]):$('#gameCustomerContact').value.trim();if(!target){$('#gameFormMessage').textContent='Field data_no belum diisi atau mapping form belum benar.';return;}if(!simple&&(!customerName||!contact)){ $('#gameFormMessage').textContent='Lengkapi nama dan kontak pembeli.';return;}$('#gameFormMessage').textContent='';openOrderConfirmation({service:selectedService.code,target,zone,additional_data:additional,form_data:values,customer_name:customerName,customer_contact:contact},values,customerName,contact);};
}
if($('#gameGrid'))initCatalog();if($('#gameOrderForm'))initDetail();
})();
