(()=>{
 const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
 const qs=new URLSearchParams(location.search),invoice=String(qs.get('invoice')||'').trim();
 const loading=document.querySelector('#paymentLoading'),content=document.querySelector('#paymentContent'),message=document.querySelector('#paymentMessage');
 const statusText={pending:'Menunggu',completed:'Berhasil',expired:'Kedaluwarsa',cancelled:'Dibatalkan',failed:'Gagal'};
 let timer=null,polling=true,current=null;
 async function headers(json=false){return KivoAuth.authHeaders(json?{'Content-Type':'application/json'}:{});}
 async function api(url,options={}){const response=await fetch(url,{cache:'no-store',...options,headers:{...(await headers(!!options.body)),...(options.headers||{})}});const raw=await response.text();let data={};try{data=raw?JSON.parse(raw):{};}catch{}if(!response.ok)throw new Error(data.error||'Terjadi kesalahan pada server.');return data;}
 function renderQr(d){const el=document.querySelector('#paymentQr');el.innerHTML='';if(d.qr_image){const img=document.createElement('img');img.src=d.qr_image;img.alt='QRIS deposit';el.appendChild(img);}else if(d.qr_content&&window.QRCode){new QRCode(el,{text:d.qr_content,width:320,height:320});}else el.textContent='QRIS belum tersedia.';}
 function updateCountdown(){if(!current)return;const final=['completed','expired','cancelled','failed'].includes(current.status);const el=document.querySelector('#paymentCountdown');if(final){el.textContent=statusText[current.status]||'Selesai';clearInterval(timer);timer=null;return;}const left=Math.max(0,new Date(current.expires_at).getTime()-Date.now());if(left<=0){el.textContent='00:00';return;}const m=Math.floor(left/60000),s=Math.floor((left%60000)/1000);el.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
 function render(d,first=false){current=d;loading.hidden=true;content.hidden=false;document.querySelector('#paymentInvoice').textContent=d.invoice;document.querySelector('#paymentTotal').textContent=rupiah(d.payment_amount);document.querySelector('#paymentAmount').textContent=rupiah(d.amount);const badge=document.querySelector('#paymentStatusBadge');badge.className='payment-status '+d.status;badge.textContent=statusText[d.status]||d.status;const live=document.querySelector('#paymentLiveStatus');live.className='deposit-live '+d.status;const cancel=document.querySelector('#cancelDepositBtn');if(d.status==='completed'){live.textContent='Deposit berhasil. Saldo sudah ditambahkan.';message.className='payment-message success';message.textContent='Pembayaran berhasil diproses.';}else if(d.status==='cancelled'){live.textContent='Deposit telah dibatalkan.';}else if(d.status==='expired'){live.textContent='Invoice sudah kedaluwarsa.';}else if(d.status==='failed'){live.textContent='Deposit tidak dapat diproses.';}else live.textContent='Menunggu pembayaran dan mencocokkan mutasi...';cancel.disabled=d.status!=='pending';cancel.textContent=d.status==='cancelled'?'Deposit Dibatalkan':'Batalkan Deposit';if(first)renderQr(d);updateCountdown();if(!timer&&!['completed','expired','cancelled','failed'].includes(d.status))timer=setInterval(updateCountdown,1000);if(['completed','expired','cancelled','failed'].includes(d.status))polling=false;}
 async function check(first=false){const data=await api('/api/check-deposit?invoice='+encodeURIComponent(invoice));render(data.deposit,first);}
 async function poll(){while(polling){try{await check(false);}catch(e){message.textContent='Mengecek ulang pembayaran...';}if(polling)await new Promise(r=>setTimeout(r,4000));}}
 document.querySelector('#copyDepositInvoice').onclick=async e=>{await navigator.clipboard.writeText(invoice);e.currentTarget.textContent='Invoice Tersalin';setTimeout(()=>e.currentTarget.textContent='Salin Invoice',1600);};
 document.querySelector('#cancelDepositBtn').onclick=async e=>{if(!current||current.status!=='pending')return;if(!confirm('Batalkan deposit ini? Jangan membayar QRIS setelah dibatalkan.'))return;const btn=e.currentTarget;btn.disabled=true;btn.textContent='Membatalkan...';message.textContent='';try{const data=await api('/api/cancel-deposit',{method:'POST',body:JSON.stringify({invoice})});render(data.deposit,false);message.className='payment-message success';message.textContent=data.message||'Deposit berhasil dibatalkan.';}catch(err){message.className='payment-message';message.textContent=err.message;btn.disabled=false;btn.textContent='Batalkan Deposit';}};
 (async()=>{if(!invoice){loading.innerHTML='<p>Invoice tidak ditemukan.</p>';return;}try{await check(true);poll();}catch(e){loading.innerHTML=`<p>${e.message}</p>`;}})();
})();
