(async()=>{
 const grid=document.querySelector('#pluginGrid'),msg=document.querySelector('#pluginMessage'),select=document.querySelector('#botSelect');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 async function headers(){const s=await KivoAuth.session();if(!s){location.href='login.html';throw new Error('Silakan login.')}return{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'}}
 async function fetchOrders(){const r=await fetch('/api/bot-orders',{headers:await headers()});const b=await r.json();if(!r.ok)throw new Error(b.error||'Gagal memuat bot.');return (b.orders||[]).filter(o=>o.session_id&&!['expired','deleted','failed'].includes(o.status))}
 async function api(invoice,options={}){const r=await fetch(`/api/bot-plugins${options.method==='POST'?'':`?invoice=${encodeURIComponent(invoice)}`}`,{...options,headers:{...(await headers()),...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Gagal memproses plugin.');return b}
 const initials={"group-pro":"GP","sticker-media":"SM",downloader:"DL","ai-tools":"AI",games:"GM"};
 function render(plugins){grid.innerHTML=plugins.map(p=>`<article class="plugin-card ${p.installed?'installed':''}"><div class="plugin-icon">${esc(initials[p.id]||'PL')}</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="plugin-status">${p.installed?'TERPASANG':'BELUM TERPASANG'}</div><button class="${p.installed?'remove':''}" data-id="${esc(p.id)}" data-installed="${p.installed}">${p.installed?'Nonaktifkan':'Pasang Sekarang'}</button></article>`).join('');grid.querySelectorAll('button').forEach(btn=>btn.onclick=()=>toggle(btn))}
 async function loadPlugins(){if(!select.value){grid.innerHTML='';msg.textContent='Pilih bot terlebih dahulu.';return}msg.textContent='Memuat plugin...';try{const b=await api(select.value);render(b.plugins||[]);msg.textContent=''}catch(e){msg.textContent=e.message}}
 async function toggle(btn){btn.disabled=true;const installed=btn.dataset.installed==='true';try{msg.textContent=installed?'Menonaktifkan plugin...':'Memasang plugin...';await api(select.value,{method:'POST',body:JSON.stringify({invoice:select.value,plugin_id:btn.dataset.id,installed:!installed})});await loadPlugins()}catch(e){msg.textContent=e.message}finally{btn.disabled=false}}
 async function init(){try{const orders=await fetchOrders();if(!orders.length){select.innerHTML='<option value="">Belum ada bot aktif</option>';msg.textContent='Kamu belum memiliki bot aktif.';return}select.innerHTML=orders.map(o=>`<option value="${esc(o.invoice)}">${esc(o.bot_name||'KEIINEXUS')} — ${esc(o.phone)} (${esc(o.status)})</option>`).join('');const wanted=new URLSearchParams(location.search).get('invoice');if(wanted&&orders.some(o=>o.invoice===wanted))select.value=wanted;await loadPlugins()}catch(e){msg.textContent=e.message}}
 select.onchange=loadPlugins;document.querySelector('#refreshPlugins').onclick=init;await init();
})();
