(()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const fmt=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
async function waitAuth(timeout=12000){const t=Date.now();while(Date.now()-t<timeout){if(window.KivoAuth?.db){const s=await KivoAuth.session().catch(()=>null);if(s)return s}await sleep(180)}return null}
async function api(url,opt={},tries=2){let last;for(let i=0;i<=tries;i++){try{const h=await KivoAuth.authHeaders({'Content-Type':'application/json',...(opt.headers||{})});const r=await fetch(`${url}${url.includes('?')?'&':'?'}_=${Date.now()}`,{...opt,headers:h,cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.error||'Terjadi kesalahan.'),{status:r.status,data:j});return j}catch(e){last=e;if(i<tries)await sleep(650*(i+1))}}throw last}
function setState(mode,msg=''){ $('#resellerLoading').hidden=mode!=='loading';$('#resellerError').hidden=mode!=='error';$('#joinView').hidden=mode!=='join';if(mode==='error')$('#resellerErrorText').textContent=msg||'Gagal memuat data reseller.' }
function petals(){const h=$('.rs-petal-field');if(!h||h.children.length)return;for(let i=0;i<14;i++){const p=document.createElement('i');p.style.setProperty('--x',`${Math.random()*100}vw`);p.style.setProperty('--d',`${10+Math.random()*12}s`);p.style.setProperty('--delay',`${-Math.random()*18}s`);p.style.setProperty('--size',`${5+Math.random()*8}px`);h.appendChild(p)}}
function motion(){const c=$('#joinCharacter');if(!c)return;addEventListener('pointermove',e=>{if(innerWidth<800)return;c.style.setProperty('--mx',`${(e.clientX/innerWidth-.5)*12}px`);c.style.setProperty('--my',`${(e.clientY/innerHeight-.5)*8}px`)},{passive:true})}
const fallbackBenefits=[{"title":"Harga Khusus Reseller","description":"Dapatkan harga khusus pada produk pilihan sehingga kamu punya ruang untuk menentukan margin jual.","active":true},{"title":"Katalog Eksklusif","description":"Akses produk dan varian yang disiapkan khusus untuk reseller dan tidak tercampur dengan katalog user biasa.","active":true},{"title":"Saldo Tetap Satu","description":"Tidak perlu membuat dompet baru. Pembayaran reseller langsung menggunakan Saldo KivoPay utama.","active":true},{"title":"Riwayat & Data Akun","description":"Invoice, status pesanan, data produk, dan catatan admin tersimpan di dashboard reseller.","active":true},{"title":"Materi Promosi","description":"Tersedia area materi promosi yang bisa disalin, diedit, lalu dipakai untuk membantu penjualan.","active":true},{"title":"Dashboard Partner","description":"Kelola katalog, order, saldo, dan informasi reseller dari halaman khusus yang terpisah dari dashboard user.","active":true}];
function renderBenefits(cfg={}){const title=$('#benefitTitle'),intro=$('#benefitIntro'),grid=$('#benefitGrid'),noteTitle=$('#benefitNoteTitle'),noteText=$('#benefitNoteText');if(title)title.textContent=cfg.title||'Yang kamu dapat sebagai Reseller KivoPay';if(intro)intro.textContent=cfg.intro||'Bukan sekadar harga lebih murah. Semua benefit reseller dibuat supaya proses jualan lebih rapi dari satu akun.';if(noteTitle)noteTitle.textContent=cfg.note_title||'Pembayaran pendaftaran menggunakan Saldo KivoPay.';if(noteText)noteText.textContent=cfg.note_text||'Setelah berhasil, akses reseller aktif otomatis pada akun yang sama.';const items=(Array.isArray(cfg.items)&&cfg.items.length?cfg.items:fallbackBenefits).filter(x=>x.active!==false);if(grid)grid.innerHTML=items.map((x,i)=>`<article class="${String(x.description||'').includes('\n')?'benefit-has-lines':''}"><span>${String(i+1).padStart(2,'0')}</span><strong>${escapeHtml(x.title)}</strong><p>${escapeHtml(x.description)}</p></article>`).join('')}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function boot(){setState('loading');const session=await waitAuth();if(!session){location.replace('login.html?next=reseller.html');return}try{const s=await api('/api/reseller-status');if(s.membership?.status==='active'){location.replace('reseller-dashboard.html');return}$('#joinPrice').textContent=fmt(s.settings?.join_price);$('#joinBalance').textContent=fmt(s.balance);const title=document.querySelector('.rs-join h1'),subtitle=document.querySelector('.rs-join-copy>p');if(title&&s.settings?.title)title.innerHTML=escapeHtml(s.settings.title).replace(/\n/g,'<br>');if(subtitle&&s.settings?.subtitle)subtitle.textContent=s.settings.subtitle;renderBenefits(s.settings?.benefits||{});$('#joinBtn').disabled=!s.settings?.is_open;$('#joinNote').textContent=s.settings?.is_open?'Aktif otomatis setelah pembayaran saldo berhasil.':'Pendaftaran sedang ditutup.';setState('join')}catch(e){if(e.status===401){location.replace('login.html?next=reseller.html');return}setState('error',e.message)}}
$('#retryReseller')?.addEventListener('click',boot);
$('.rs-detail-benefit-btn')?.addEventListener('click',e=>{e.preventDefault();const target=$('#benefitReseller');if(!target)return;target.hidden=false;target.scrollIntoView({behavior:'smooth',block:'start'});});
$('#joinBtn')?.addEventListener('click',async()=>{if(!confirm('Biaya reseller akan dipotong dari Saldo KivoPay. Lanjutkan?'))return;const b=$('#joinBtn');try{b.disabled=true;b.textContent='Memproses...';await api('/api/join-reseller',{method:'POST',body:'{}'},0);location.replace('reseller-dashboard.html')}catch(e){if(e.data?.need_deposit&&confirm(`${e.message}
Buka halaman deposit?`))location.href='deposit.html';else alert(e.message);b.disabled=false;b.textContent='Gabung Reseller'}});const start=()=>{petals();motion();boot()};document.readyState==='loading'?addEventListener('DOMContentLoaded',start):start()})();