(()=>{const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));let state={items:[],membership:null,balance:0,current:null};
async function api(url,opt={}){const h=await KivoAuth.authHeaders({'Content-Type':'application/json',...(opt.headers||{})});const r=await fetch(url,{...opt,headers:h});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.error||'Terjadi kesalahan.'),{status:r.status,data:j});return j}

function petals(){const host=document.querySelector('.rs-petal-field');if(!host)return;for(let i=0;i<16;i++){const p=document.createElement('i');p.style.setProperty('--x',`${Math.random()*100}vw`);p.style.setProperty('--d',`${9+Math.random()*12}s`);p.style.setProperty('--delay',`${-Math.random()*18}s`);p.style.setProperty('--size',`${5+Math.random()*8}px`);host.appendChild(p)}}
function characterMotion(){const stage=document.querySelector('#joinCharacter');if(!stage)return;window.addEventListener('pointermove',e=>{if(innerWidth<760)return;stage.style.setProperty('--mx',`${(e.clientX/innerWidth-.5)*12}px`);stage.style.setProperty('--my',`${(e.clientY/innerHeight-.5)*8}px`)},{passive:true})}
async function boot(){const session=await KivoAuth.session();if(!session)return location.replace('login.html?next=reseller.html');try{const s=await api('/api/reseller-status');state.balance=s.balance;$('#joinPrice').textContent=fmt(s.settings.join_price);$('#joinBalance').textContent=fmt(s.balance);if(s.membership?.status==='active'){return location.replace('reseller-dashboard.html')}else{$('#joinView').hidden=false;$('#joinBtn').disabled=!s.settings.is_open;$('#joinNote').textContent=s.settings.is_open?'Aktif otomatis setelah pembayaran saldo berhasil.':'Pendaftaran sedang ditutup.'}}catch(e){alert(e.message)}}
function renderCatalog(q=''){const list=state.items.filter(x=>x.product.name.toLowerCase().includes(q.toLowerCase()));$('#catalogGrid').innerHTML=list.length?list.map((x,i)=>`<article class="rs-product" style="animation-delay:${i*55}ms"><img src="${x.product.image_url||'icons/icon-512.png'}" alt=""><small>${x.is_exclusive?'KHUSUS RESELLER':'HARGA RESELLER'}</small><h3>${esc(x.product.name)}</h3><p>${esc(x.promo_text||x.product.description||'Produk digital pilihan KivoPay.')}</p><div class="price"><div><strong>${fmt(x.reseller_price)}</strong><del>${fmt(x.product.price)}</del></div><span>Stok ${Number(x.product.stock||0)}</span></div><button data-buy="${x.product_id}">Order Sekarang</button></article>`).join(''):'<p>Produk reseller belum tersedia.</p>'}
async function loadOrders(){const r=await api('/api/reseller-orders');const data=r.orders||[];$('#orderCount').textContent=data.length;$('#orderList').innerHTML=data.map(o=>`<article class="rs-order"><div><strong>${esc(o.product_name)}</strong><small>${esc(o.invoice)} · ${esc(o.variant_name||'Paket')}</small>${o.admin_note?`<small>${esc(o.admin_note)}</small>`:''}${o.delivery_content?`<small>${esc(o.delivery_content)}</small>`:''}</div><div><strong>${fmt(o.amount)}</strong><small>${esc(o.status)}</small></div></article>`).join('')||'<p>Belum ada order reseller.</p>'}
function openOrder(id){state.current=state.items.find(x=>String(x.product_id)===String(id));if(!state.current)return;const p=state.current.product,v=Array.isArray(p.variants)&&p.variants.length?p.variants:[{name:'Paket utama'}];$('#modalTitle').textContent=p.name;$('#variantSelect').innerHTML=v.map((x,i)=>`<option value="${i}">${esc(x.name||'Paket utama')}</option>`).join('');$('#emailField').hidden=!p.requires_email;updatePrice();$('#orderModal').hidden=false}
function updatePrice(){const p=state.current.product,v=p.variants?.[$('#variantSelect').value]||{name:'Paket utama'};$('#modalPrice').textContent=fmt(state.current.variant_prices?.[v.name]??state.current.reseller_price)}
$('#joinBtn').onclick=async()=>{if(!confirm('Biaya reseller akan dipotong dari Saldo KivoPay. Lanjutkan?'))return;try{$('#joinBtn').disabled=true;const r=await api('/api/join-reseller',{method:'POST',body:'{}'});state.membership=r.membership;state.balance=Number(r.balance_after??state.balance);location.reload()}catch(e){if(e.data?.need_deposit&&confirm(`${e.message}\nBuka halaman deposit?`))location.href='deposit.html';else alert(e.message);$('#joinBtn').disabled=false}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-buy]');if(b)openOrder(b.dataset.buy)});$('#variantSelect').onchange=updatePrice;$('#closeModal').onclick=()=>$('#orderModal').hidden=true;$('#orderModal').onclick=e=>{if(e.target===$('#orderModal'))$('#orderModal').hidden=true};$('#searchProduct').oninput=e=>renderCatalog(e.target.value);document.querySelectorAll('.rs-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.rs-tabs button,.rs-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab+'Tab').classList.add('active')});$('#copyPromo').onclick=async()=>{await navigator.clipboard.writeText($('#promoText').value);$('#copyPromo').textContent='Tersalin';setTimeout(()=>$('#copyPromo').textContent='Salin Teks',1300)};
$('#submitOrder').onclick=async()=>{const msg=$('#orderMessage');msg.textContent='';const body={product_id:state.current.product_id,variant_index:Number($('#variantSelect').value),customer_name:$('#buyerName').value.trim(),customer_contact:$('#buyerWhatsapp').value.trim(),customer_email:$('#buyerEmail').value.trim()};try{$('#submitOrder').disabled=true;$('#submitOrder').textContent='Memproses...';const r=await api('/api/create-reseller-order',{method:'POST',body:JSON.stringify(body)});state.balance=Number(r.balance_after??state.balance);$('#mainBalance').textContent=fmt(state.balance);$('#orderModal').hidden=true;await loadOrders();alert('Order reseller berhasil dibuat.')}catch(e){msg.textContent=e.message;if(e.data?.need_deposit)msg.innerHTML+=` <a href="deposit.html">Deposit saldo</a>`}finally{$('#submitOrder').disabled=false;$('#submitOrder').textContent='Bayar dengan Saldo'}};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}const start=()=>{petals();characterMotion();boot()};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start()})();
