(()=>{const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0)),dt=v=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(v)):'-';let rows=[];
function invoices(){try{return JSON.parse(localStorage.getItem('kivopay_game_invoices')||'[]').filter(Boolean)}catch{return[]}}
function statusLabel(s){return({pending:'Menunggu Pembayaran',paid:'Pembayaran Masuk',processing:'Sedang Diproses',completed:'Berhasil',failed:'Gagal',expired:'Kedaluwarsa'})[s]||s}
function logs(o){const out=[['Pesanan dibuat',o.created_at,'QRIS dibuat dan menunggu pembayaran.']];if(o.paid_at)out.push(['Pembayaran diterima',o.paid_at,'Pembayaran QRIS berhasil terdeteksi.']);if(o.provider_id)out.push(['Dikirim ke provider',o.updated_at,`ID transaksi: ${o.provider_id}`]);if(o.completed_at)out.push(['Pesanan selesai',o.completed_at,o.note||'Produk berhasil dikirim.']);else if(o.status==='failed')out.push(['Pesanan gagal',o.updated_at,o.note||'Provider menolak pesanan.']);else if(o.status==='processing')out.push(['Provider memproses',o.updated_at,o.note||'Pesanan sedang diproses provider.']);return out}
function mask(k,v){const key=String(k||'').toLowerCase();if(/password|pass|pin|backup|security|kode/.test(key))return v?'••••••••':'-';return String(v||'-')}
function fieldRank(k){const x=String(k||'').toLowerCase();if(/^(target|user_?id|userid|uid|id_?game|data_?no)$/.test(x)||(/user|uid|target|data_no/.test(x)&&!/zone|server/.test(x)))return 0;if(/zone|server/.test(x))return 1;return 2}
function orderedEntries(o){return Object.entries(o.form_data||{}).filter(([,v])=>String(v??'').trim()).sort((a,b)=>fieldRank(a[0])-fieldRank(b[0]))}
function target(o){if(o.target)return `${o.target}${o.zone?` / ${o.zone}`:''}`;const entries=orderedEntries(o);return entries.length?entries.map(([k,v])=>`${k.replace(/_/g,' ')}: ${mask(k,v)}`).join(' • '):'-'}
function formRows(o){const entries=orderedEntries(o);return entries.map(([k,v])=>`<dt>${esc(k.replace(/_/g,' '))}</dt><dd>${esc(mask(k,v))}</dd>`).join('')}
function render(){const q=$('#historySearch').value.toLowerCase(),st=$('#historyStatus').value;const list=rows.filter(o=>(st==='all'||o.status===st)&&[o.invoice,o.game_name,o.service_name,o.target,o.provider_id].join(' ').toLowerCase().includes(q));$('#gameHistoryList').innerHTML=list.length?list.map(o=>`<article class="kivo-history-card"><div class="history-card-top"><div><small>Invoice KivoPay</small><strong>${esc(o.invoice)}</strong></div><span class="history-status ${esc(o.status)}">${esc(statusLabel(o.status))}</span></div><h2>${esc(o.game_name)}</h2><p>${esc(o.service_name)}</p><div class="history-info-grid"><div><small>Tujuan</small><strong>${esc(target(o))}</strong></div><div><small>Total</small><strong>${rp(o.payment_amount)}</strong></div><div><small>ID Trx Provider</small><strong>${esc(o.provider_id||'Belum tersedia')}</strong></div><div><small>Tanggal</small><strong>${esc(dt(o.created_at))}</strong></div></div><button class="history-detail-btn" data-invoice="${esc(o.invoice)}">Lihat Detail & Log</button></article>`).join(''):'<section class="history-empty"><h2>Belum ada riwayat</h2><p>Pesanan yang dibuat dari perangkat ini akan tampil di sini.</p><a href="topup-game.html">Mulai Top Up</a></section>';document.querySelectorAll('[data-invoice]').forEach(b=>b.onclick=()=>openDetail(b.dataset.invoice))}
function openDetail(inv){const o=rows.find(x=>x.invoice===inv);if(!o)return;$('#historyDetailBody').innerHTML=`<span class="eyebrow">DETAIL PESANAN</span><h2>${esc(o.game_name)}</h2><p class="detail-service">${esc(o.service_name)}</p><dl class="history-detail-grid"><dt>Invoice</dt><dd>${esc(o.invoice)}</dd><dt>ID Transaksi Provider</dt><dd>${esc(o.provider_id||'-')}</dd>${formRows(o)||`<dt>Data tujuan</dt><dd>${esc(target(o))}</dd>`}<dt>Kontak pembeli</dt><dd>${esc(o.customer_contact||'-')}</dd><dt>Total bayar</dt><dd>${rp(o.payment_amount)}</dd><dt>Status provider</dt><dd>${esc(o.provider_status||statusLabel(o.status))}</dd><dt>Catatan</dt><dd>${esc(o.note||'-')}</dd></dl><h3>Log Proses</h3><div class="order-timeline">${logs(o).map((x,i)=>`<div class="timeline-item ${i===logs(o).length-1?'active':''}"><i></i><div><strong>${esc(x[0])}</strong><small>${esc(dt(x[1]))}</small><p>${esc(x[2])}</p></div></div>`).join('')}</div>`;$('#historyDetail').showModal()}
async function fetchJson(url,opt){const r=await fetch(url,opt),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{throw new Error('Server mengirim halaman HTML, bukan data transaksi.')}if(!r.ok)throw new Error(d.error||'Gagal memuat transaksi.');return d}
let loading=false;async function load(){if(loading)return;loading=true;try{const ids=invoices();if(!ids.length){rows=[];return render()}try{const d=await fetchJson('/api/game-order-history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({invoices:ids}),cache:'no-store'});rows=d.orders||[]}catch(historyError){const results=await Promise.allSettled(ids.slice(0,100).map(inv=>fetchJson('/api/check-game-payment?invoice='+encodeURIComponent(inv),{cache:'no-store'})));rows=results.filter(x=>x.status==='fulfilled'&&x.value?.order).map(x=>x.value.order).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(!rows.length)throw historyError}render()}finally{loading=false}}
$('#historySearch').oninput=render;$('#historyStatus').onchange=render;$('#closeHistoryDetail').onclick=()=>$('#historyDetail').close();$('#historyDetail').onclick=e=>{if(e.target===$('#historyDetail'))$('#historyDetail').close()};load().catch(e=>{loading=false;$('#gameHistoryList').innerHTML=`<section class="history-empty"><h2>Riwayat gagal dimuat</h2><p>${esc(e.message)}</p></section>`});setInterval(()=>{if(!document.hidden)load().catch(()=>{})},5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load().catch(()=>{})});})();
