(async()=>{
 const list=document.querySelector('#orderHistoryList'),msg=document.querySelector('#historyMessage'),form=document.querySelector('#invoiceHistoryForm'),input=document.querySelector('#invoiceHistoryInput');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
 const statusLabel={pending:'Menunggu pembayaran',processing:'Sedang diproses',completed:'Selesai',cancelled:'Dibatalkan',failed:'Gagal'};
 const date=v=>v?new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'-';
 let session=null;
 function card(o){const invoice=o.invoice||o.order_id||o.reference||'-',status=String(o.status||o.payment_status||'pending').toLowerCase();return `<article class="history-card"><div class="history-card-top"><div><small>${esc(invoice)}</small><h3>${esc(o.product_name||o.service_name||'Produk Digital')}</h3></div><span class="history-status ${esc(status)}">${esc(statusLabel[status]||status)}</span></div><div class="history-meta"><span><b>Paket</b>${esc(o.variant_name||o.package_name||'Paket utama')}</span><span><b>Total</b>${money(o.payment_amount??o.amount)}</span><span><b>Tanggal</b>${esc(date(o.created_at||o.updated_at))}</span></div><div class="history-actions"><a href="payment-order.html?invoice=${encodeURIComponent(invoice)}">Lihat Detail</a><button type="button" data-copy="${esc(invoice)}">Salin Invoice</button></div>${o.delivery_content&&status==='completed'?`<div class="history-delivery"><small>DATA PRODUK</small><pre>${esc(o.delivery_content)}</pre></div>`:''}</article>`}
 function bind(){document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Tersalin ✓'})}
 async function byInvoice(inv){msg.textContent='Mencari invoice...';list.innerHTML='';try{const r=await fetch('/api/check-payment?invoice='+encodeURIComponent(inv),{cache:'no-store'}),d=await r.json();if(!r.ok||!d.order)throw new Error(d.error||'Invoice tidak ditemukan');list.innerHTML=card(d.order);msg.textContent='1 pesanan ditemukan.';bind();}catch(e){msg.textContent=e.message||'Invoice tidak ditemukan.'}}
 async function load(){list.innerHTML='';msg.textContent='Memuat riwayat pesanan...';session=await KivoAuth.session();if(!session){msg.innerHTML='Masuk ke akun untuk melihat semua pesanan otomatis. <a href="login.html">Masuk sekarang</a>';return;}try{const {data,error}=await KivoAuth.db.from('orders').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(50);if(error)throw error;if(!data?.length){msg.textContent='Belum ada pesanan pada akun ini.';return;}list.innerHTML=data.map(card).join('');msg.textContent=`${data.length} pesanan tersimpan.`;bind();}catch(e){msg.textContent='Riwayat belum bisa dimuat. Kamu tetap dapat mencari menggunakan invoice.'}}
 form.onsubmit=e=>{e.preventDefault();const inv=input.value.trim();if(inv)byInvoice(inv)};
 document.querySelector('#refreshHistory').onclick=load;
 const q=new URLSearchParams(location.search).get('invoice');if(q){input.value=q;await byInvoice(q)}else await load();
})();
