(async()=>{
 const list=document.querySelector('#orderHistoryList'),msg=document.querySelector('#historyMessage'),form=document.querySelector('#invoiceHistoryForm'),input=document.querySelector('#invoiceHistoryInput');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
 const labels={pending:'Menunggu pembayaran',paid:'Pembayaran masuk',processing:'Sedang diproses',completed:'Selesai',cancelled:'Dibatalkan',failed:'Gagal'};
 const date=v=>v?new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'-';
 const snapshots=()=>{try{return JSON.parse(localStorage.getItem('kivopay_order_snapshots')||'[]').filter(Boolean)}catch{return[]}};
 const invoices=()=>{try{return JSON.parse(localStorage.getItem('kivopay_order_invoices')||'[]').filter(Boolean)}catch{return[]}};
 function save(o){if(!o?.invoice)return;try{const all=snapshots();localStorage.setItem('kivopay_order_snapshots',JSON.stringify([o,...all.filter(x=>x?.invoice!==o.invoice)].slice(0,100)));const ids=invoices();localStorage.setItem('kivopay_order_invoices',JSON.stringify([o.invoice,...ids.filter(x=>x!==o.invoice)].slice(0,100)));}catch{}}
 function card(o){const inv=o.invoice||'-',st=String(o.status||'pending').toLowerCase();return `<article class="history-card"><div class="history-card-top"><div><small>${esc(inv)}</small><h3>${esc(o.product_name||'Produk Digital')}</h3></div><span class="history-status ${esc(st)}">${esc(labels[st]||st)}</span></div><div class="history-meta"><span><b>Paket</b>${esc(o.variant_name||'Paket utama')}</span><span><b>Total</b>${money(o.payment_amount??o.amount)}</span><span><b>Tanggal</b>${esc(date(o.created_at||o.updated_at))}</span></div><div class="history-actions"><a href="payment-order.html?invoice=${encodeURIComponent(inv)}">Lihat Detail</a><button type="button" data-copy="${esc(inv)}">Salin Invoice</button></div></article>`}
 function bind(){document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Tersalin ✓'})}
 function render(rows){const unique=[...new Map(rows.filter(Boolean).map(o=>[o.invoice,o])).values()].sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0));if(!unique.length){list.innerHTML='';msg.textContent='Belum ada riwayat pesanan yang tersimpan.';return;}list.innerHTML=unique.map(card).join('');msg.textContent=`${unique.length} pesanan tersimpan permanen di akun/perangkat ini.`;bind();}
 async function fetchInvoice(inv){const r=await fetch('/api/check-payment?invoice='+encodeURIComponent(inv),{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.order)throw new Error(d.error||'Invoice tidak ditemukan');save(d.order);return d.order}
 async function load(){msg.textContent='Menyinkronkan riwayat...';const local=snapshots();let account=[];try{const session=await KivoAuth.session();if(session){const {data,error}=await KivoAuth.db.from('orders').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(100);if(!error)account=data||[];}}catch{}
 const missing=invoices().filter(inv=>![...local,...account].some(o=>o.invoice===inv)).slice(0,30);const fetched=(await Promise.allSettled(missing.map(fetchInvoice))).filter(x=>x.status==='fulfilled').map(x=>x.value);render([...account,...fetched,...local]);}
 form.onsubmit=async e=>{e.preventDefault();const inv=input.value.trim();if(!inv)return;msg.textContent='Mencari invoice...';try{render([await fetchInvoice(inv)])}catch(err){msg.textContent=err.message||'Invoice tidak ditemukan.'}};
 document.querySelector('#refreshHistory').onclick=load;const q=new URLSearchParams(location.search).get('invoice');if(q){input.value=q;form.requestSubmit()}else load();
})();
